/**:
  ros__parameters:
    min_longitudinal_offset: 2.375
    max_longitudinal_offset: 2.395
    min_lateral_offset: -0.97
    max_lateral_offset: 1.19
    min_height_offset: 1.0
    max_height_offset: 1.16
